
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.esplugin]
audit-as-crates-io = false

[[exemptions.criterion]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASI, which is not an intended target."

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.linux-raw-sys]]
version = "0.11.0"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASI, which is not an intended target."

[[exemptions.memchr]]
version = "2.7.5"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting UEFI, which is not an intended target."

[[exemptions.rustix]]
version = "1.1.2"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASI, which is not an intended target."

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"
suggest = false
notes = "It's a collection of static library binaries and a build script that configures Cargo to use them, so it's not really reviewable."

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"
suggest = false
notes = "It's a collection of static library binaries and a build script that configures Cargo to use them, so it's not really reviewable."
